using DevExpress.ExpressApp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace UIS.ExpressApp.Erhebung.Module
{
    public static class Function
    {

        /// <summary>Shows a Message withn Xaf MessageOption</summary>
        /// <param name="Caption">The Caption of the Message Window.</param>
        /// <param name="Message">The message text of the Message.</param>
        /// <param name="it">Information Type of the Message</param>
        /// <param name="Application">The application object</param>
        /// <autogeneratedoc />
        public static void ShowMessage(string Caption, string Message, InformationType it, XafApplication Application)
        {
            MessageOptions options = new MessageOptions
            {
                Duration = 10000,
                Message = Message,
                Type = it
            };
            options.Web.Position = InformationPosition.Top;
            options.Win.Caption = Caption;
            options.Win.Type = WinMessageType.Flyout;
            Application.ShowViewStrategy.ShowMessage(options);
        }
    }
}
